syntax = "proto2";

option csharp_namespace = "SteamAuth.Protocol";

message CPhone_IsAccountWaitingForEmailConfirmation_Request {}

message CPhone_IsAccountWaitingForEmailConfirmation_Response {
  optional bool awaiting_email_confirmation = 1;
  optional uint32 seconds_to_wait = 2;
}

message CPhone_SendPhoneVerificationCode_Request {
  optional uint32 language = 1;
}

message CPhone_SendPhoneVerificationCode_Response {}

message CPhone_SetAccountPhoneNumber_Request {
  optional string phone_number = 1;
  optional string phone_country_code = 2;
}

message CPhone_SetAccountPhoneNumber_Response {
  optional string confirmation_email_address = 1;
  optional string phone_number_formatted = 2;
}

message CPhone_VerifyAccountPhoneWithCode_Request {
  optional string code = 1;
}

message CPhone_VerifyAccountPhoneWithCode_Response {}

message CPhone_AccountPhoneStatus_Request {}

message CPhone_AccountPhoneStatus_Response {
  optional bool has_phone = 1;
}
