syntax = "proto2";

option csharp_namespace = "SteamAuth.Protocol";

enum ETokenRenewalType {
  k_ETokenRenewalType_None = 0;
  k_ETokenRenewalType_Allow = 1;
}

enum EAuthTokenPlatformType {
  k_EAuthTokenPlatformType_Unknown = 0;
  k_EAuthTokenPlatformType_SteamClient = 1;
  k_EAuthTokenPlatformType_WebBrowser = 2;
  k_EAuthTokenPlatformType_MobileApp = 3;
}

enum EAuthSessionSecurityHistory {
  k_EAuthSessionSecurityHistory_Invalid = 0;
  k_EAuthSessionSecurityHistory_UsedPreviously = 1;
  k_EAuthSessionSecurityHistory_NoPriorHistory = 2;
}

enum ESessionPersistence {
  k_ESessionPersistence_Invalid = -1;
  k_ESessionPersistence_Ephemeral = 0;
  k_ESessionPersistence_Persistent = 1;
}

message CAuthentication_AccessToken_GenerateForApp_Request {
  optional string refresh_token = 1;
  optional fixed64 steamid = 2;
  optional ETokenRenewalType renewal_type = 3 [default = k_ETokenRenewalType_None];
}

message CAuthentication_AccessToken_GenerateForApp_Response {
  optional string access_token = 1;
  optional string refresh_token = 2;
}

message CAuthentication_GetAuthSessionsForAccount_Request {
}

message CAuthentication_GetAuthSessionsForAccount_Response {
  repeated uint64 client_ids = 1;
}

message CAuthentication_GetAuthSessionInfo_Request {
  optional uint64 client_id = 1;
}

message CAuthentication_GetAuthSessionInfo_Response {
  optional string ip = 1;
  optional string geoloc = 2;
  optional string city = 3;
  optional string state = 4;
  optional string country = 5;
  optional EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];
  optional string device_friendly_name = 7;
  optional int32 version = 8;
  optional EAuthSessionSecurityHistory login_history = 9 [default = k_EAuthSessionSecurityHistory_Invalid];
  optional bool requestor_location_mismatch = 10;
  optional bool high_usage_login = 11;
  optional ESessionPersistence requested_persistence = 12 [default = k_ESessionPersistence_Invalid];
}

message CAuthentication_UpdateAuthSessionWithMobileConfirmation_Request {
  optional int32 version = 1;
  optional uint64 client_id = 2;
  optional fixed64 steamid = 3;
  optional bytes signature = 4;
  optional bool confirm = 5 [default = false];
  optional ESessionPersistence persistence = 6 [default = k_ESessionPersistence_Persistent];
}

message CAuthentication_UpdateAuthSessionWithMobileConfirmation_Response {
}
